config/routes.rb
Rails.application.routes.draw do
  get 'prints/index', to: 'prints#index', as: 'prints'
  get 'prints/prints_admin', to: 'prints#prints_admin', as: 'prints_admin'
  get 'prints/show/:id', to: 'prints#show', as: 'print'
  post '/add_to_cart_prints/:id', to: "prints#add_to_cart_prints", as: 'add_to_cart_prints'
  delete '/remove_from_cart_prints/:id', to: "prints#remove_from_cart_prints", as: 'remove_from_cart_prints'
  get '/publish_print/:id', to: "prints#publish_print", as: 'publish_print'
  get '/unpublish_print/:id', to: "prints#unpublish_print", as: 'unpublish_print'
  # resources :nfts, only: [ :index ] do
  #   collection do
  #     post 'set_image_urls'
  #     # get 'nfts'
  #   end
  # end
  # post '/set_image_urls', to: 'nfts#set_image_urls', as: 'set_image_urls'
  get '/nfts', to: 'nfts#nfts', as: 'nfts'
  get '/endpoint', to: 'nfts#endpoint', as: 'endpoint'


  resources :contacts, only: [:new, :create]

  resources :paintings
  get '/admin', to: 'paintings#admin', as: 'admin'
  devise_for :users, controllers: {
    sessions: 'custom_devise/sessions'
  }
  root to: "pages#home"
  get '/cv', to: "pages#cv", as: 'cv'
  get '/about', to: "pages#about", as: 'about'
  get '/commissions', to: "pages#commissions", as: 'commissions'
  get '/privacy', to: "pages#privacy", as: 'privacy'
  get '/terms', to: "pages#terms", as: 'terms'
  get '/photography', to: "pages#photography", as: 'photography'


  post '/add_to_cart/:id', to: "paintings#add_to_cart", as: 'add_to_cart'
  delete '/remove_from_cart/:id', to: "paintings#remove_from_cart", as: 'remove_from_cart'


  get '/orders/new', to: "orders#new", as: 'new_order'
  post '/orders', to: "orders#create", as: 'create_order'
  post :create_paypal , to: "orders#create_paypal"
  get '/orders/:id', to: "orders#show", as: 'order'
  get '/orders', to: "orders#index", as: 'orders'
  get '/orders/:id/edit', to: "orders#edit", as: 'edit_order'
  patch '/orders/:id', to: "orders#update", as: 'update_order'
  delete '/orders/:id', to: "orders#destroy", as: 'destroy_order'
  get '/alchemy', to: "orders#alchemy", as: 'alchemy'
  post '/total_price', to: "orders#total_price", as: 'total_price'
  post '/cancel_print_order', to: "orders#cancel_print_order", as: 'cancel_print_order'

  get '/wallet', to: "orders#wallet", as: 'wallet'
  get '/btcwallet', to: "orders#btcwallet", as: 'btcwallet'
end

app/controllers/prints_controller.rb
require 'mail'
require 'json'
require 'uri'
require 'net/http'
require 'nokogiri'
require 'byebug'

class PrintsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index , :show, :add_to_cart_prints, :remove_from_cart_prints ]
  before_action :initalize_cart_prints, only: %i[ load_cart_prints add_to_cart_prints remove_from_cart_prints ]
  # before_action :load_products, only: :load_cart_prints
  before_action :load_cart
  # before_action :load_cart_prints
  before_action :load_orders

  def index
    @products = load_products
    if !params[:query] || params[:query].empty?
      @products = Kaminari.paginate_array(@products).page(params[:page]).per(10)
    end

    return unless params[:query].present?

    sql_subquery = <<~SQL
      products.title ILIKE :query
    SQL
    # @products = @products.select(sql_subquery, query: "%#{params[:query]}%").page params[:page]
    @products = @products.select {|p| p["title"].downcase.include?(params[:query].downcase)}
    @products = Kaminari.paginate_array(@products).page(params[:page]).per(10)

  end

  def prints_admin
    @products = load_products
  end

  def show
    # Pass the product id as a param from the index page? Or JS controller
    shop_id = ENV['PRINTIFY_SHOP_ID']
    product_id = sanitize_id(params[:id])
    url = URI("https://api.printify.com/v1/shops/#{shop_id}/products/#{product_id}.json");
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true;

    request = Net::HTTP::Get.new(url)
    request["Authorization"] = "Bearer #{ENV['PRINTIFY']}"
    request["Content-Type"] = "application/json"
    request["Accept"] = "application/json"
    request["User-Agent"] = "RUBY"
    # request.body = JSON.dump({}) # if you need to send a body with the request...

    response = http.request(request)
    raw_data = JSON.parse(response.read_body)

    print = raw_data
    images = [];
    print["images"].each do |image|
      images << image["src"]
    end

    parsed_description = Nokogiri::HTML.parse(print['description'])

    default_variant = print['variants'].find { |variant| variant['is_default'] == true && variant['is_enabled'] == true}

    variants = []
    variants = print['variants'].select { |variant| variant['is_enabled'] == true }

    if default_variant
      price = default_variant['price']
    else
      first_variant = variants.first
      price = first_variant['price']
    end

    if print["images"].empty?

      @print = {
        'id' => print['id'],
        'title' => print['title'],
        'description' => parsed_description.text,
        'image' => 'abstractart.png',
        'price' => price,
        'tags' => print['tags'],
        'variants' => variants || [default_variant]
      }
    else
      @print = {
        'id' => print['id'],
        'title' => print['title'],
        'description' => parsed_description.text,
        'images' => images,
        'price' => price,
        'tags' => print['tags'],
        'variants' => variants || [default_variant]
      }
    end

    @print

  end

  def add_to_cart_prints
    id = params[:id]
    variant_id = params[:variant_id]
    variant_title = params[:variant_title]
    session[:prints_cart] << {"id" => id, "variant_id" => variant_id, "variant_title" => variant_title }
    redirect_to new_order_path
  end

  def remove_from_cart_prints
    id = params[:id]
    print_cart = session[:prints_cart]
    index = print_cart.index { |item| item["id"] == id } # && item["variant_id"] == params[:variant_id] TO DO: Add variant_id to the session cart removal?
    print_cart.delete_at(index) if index

    # print_cart.delete_at((print_cart.find { |item| item["id"] == id }) || print_cart.length)
    # print_cart.delete_at(print_cart.index(id) || print_cart.length)
    # session[:prints_cart].delete(id)
    if print_cart.empty? && session[:cart].empty?
      redirect_to prints_path
    else
      redirect_to new_order_path
    end
  end

  def unpublish_print
    begin
      id = sanitize_id(params[:id])
      shop_id = ENV['PRINTIFY_SHOP_ID']
      url = URI("https://api.printify.com/v1/shops/#{shop_id}/products/#{id}/publishing_failed.json");
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true;
      request = Net::HTTP::Post.new(url)
      request["Authorization"] = "Bearer #{ENV['PRINTIFY']}"
      request["Content-Type"] = "application/json"
      request["Accept"] = "application/json"
      request["User-Agent"] = "RUBY"
      request.body = JSON.dump({
        reason: "I need to remove this print from my shop."
      })

      response = http.request(request)
      raw_data = JSON.parse(response.read_body)
      Rails.logger.info("==========================================")
      Rails.logger.info("Response is: #{raw_data}")
      Rails.logger.info("==========================================")

      if raw_data = "#{id}"
        flash[:notice] = "Print has been unpublished 👍, please remove it from your shop in the printify console."
      else
        flash[:notice] = "Could not unpublish the print 🚨, please try again or contact support."
      end

      redirect_to prints_admin_path
    rescue StandardError => e
      Rails.logger.error("==========================================")
      Rails.logger.error("Error is: #{e}")
      Rails.logger.error("==========================================")
      flash[:notice] = "Could not unpublish the print 🚨, please try again.
      Error: #{e}"
      redirect_to print_admin_paths
    end
  end

  def publish_print
    begin
      id = sanitize_id(params[:id])
      shop_id = ENV['PRINTIFY_SHOP_ID']
      url = URI("https://api.printify.com/v1/shops/#{shop_id}/products/#{id}/publishing_succeeded.json");
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true;
      request = Net::HTTP::Post.new(url)
      request["Authorization"] = "Bearer #{ENV['PRINTIFY']}"
      request["Content-Type"] = "application/json"
      request["Accept"] = "application/json"
      request["User-Agent"] = "RUBY"
      request.body = JSON.dump({
        external: {
          id: "#{id}",
          handle: "https://theartofjaleh.com/prints/show/#{id}"
        }
      })

      response = http.request(request)
      raw_data = JSON.parse(response.read_body)
      Rails.logger.info("==========================================")
      Rails.logger.info("Response is: #{raw_data}")
      Rails.logger.info("==========================================")

      if raw_data = "#{id}"
        flash[:notice] = "Print has been published 👍, please verify it shows as such on your Printify shop."
      else
        flash[:notice] = "Could not publish the print 🚨, please try again."
      end

      redirect_to print_path(id: id)
    rescue StandardError => e
      Rails.logger.error("==========================================")
      Rails.logger.error("Error is: #{e}")
      Rails.logger.error("==========================================")
      flash[:notice] = "Could not publish the print 🚨, please try again.
      Error: #{e}"
      redirect_to print_path(id: id)
    end

  end

  private

  def load_products
    @products = Rails.cache.fetch("products", expires_in: 1.hour) do
      shop_id = ENV['PRINTIFY_SHOP_ID']
      url = URI("https://api.printify.com/v1/shops/#{shop_id}/products.json");
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = true;

      request = Net::HTTP::Get.new(url)
      request["Authorization"] = "Bearer #{ENV['PRINTIFY']}"
      request["Content-Type"] = "application/json"
      request["Accept"] = "application/json"
      request["User-Agent"] = "RUBY"
      request["Cache-Control"] = "private, max-age=3600, no-revalidate"
      # request.body = JSON.dump({}) # if you need to send a body with the request...

      response = http.request(request)
      raw_data = JSON.parse(response.read_body)

      products = raw_data["data"]

      products = products.map do |product|
        p "=========================================="
        p "Product is: #{product["id"]}"
        p "=========================================="

        next if product['visible'] != true # Skip if product is not published

        parsed_description = Nokogiri::HTML.parse(product['description'])

        default_variant = product['variants'].find { |variant| variant['is_default'] == true && variant['is_enabled'] == true}


        if default_variant
          price = default_variant['price']
          variant = default_variant['id']
        else
          first_variant = product['variants'].first
          price = first_variant['price']
          variant = first_variant['id']
        end


        if product["images"].empty?
          {
            'id' => product['id'],
            'title' => product['title'],
            'description' => parsed_description.text,
            'image' => 'abstractart.png',
            'price' => price,
            'tags' => product['tags'], # product['variants'].first['price'],
            'variant' => variant # product['variants'].first['id']
          }
        else
          {
            'id' => product['id'],
            'title' => product['title'],
            'description' => parsed_description.text,
            'image' => product["images"].first["src"],
            'price' => price,
            'tags' => product['tags'],
            'variant' => variant
          }
        end

      end
    end
    @products = @products
  end

  def load_cart
    if session[:cart].nil?
      session[:cart] = []
      @cart = session[:cart]
    else
      @cart = Painting.find(session[:cart])
    end
  end

  def initalize_cart_prints
    session[:prints_cart] ||= []
  end

  def load_orders
    @orders = Order.all
  end

  def sanitize_id(id)
    ActionController::Base.helpers.sanitize(id)
  end

end

app/views/prints/_print.html.erb
<div class="container-fluid mt-3 text-center">
  <div id="<%= dom_id print %>">
    <div class="prod-card my-3">
    <div>BUTTS</div>
      <% if Rails.env.test? %>
          <%= image_tag "photo1.jpeg", alt: "test image" %>
        <% else %>
          <%=image_tag print["image"] %>
        <% end %>
      <h1 class="mt-3"><%= print["title"] %></h1>
      <p class="prod-price"> <%= number_to_currency(print["price"] / 100.00, :unit=> '$') %></p>
      <p><%= print["description"] %></p>
      <% puts "PRINT: #{print}"%>
      <% if !print["variants"].empty? %>
        <p>Available Sizes:</p>
        <%= select_tag "Sizes", options_for_select(print.collect{ |v| [v['title'], v['id']] })%>
      <% end %>
        <% if @prints_cart.include?(print) %>
          <%= button_to 'Remove from cart', remove_from_cart_print_path(print), method: :delete, class: 'btn btn-danger' %>
        <% else %>
          <p>
            <%= button_to "Purchase Original", add_to_cart_print_path(print), method: :post, class: "btn btn-primary mt-3" %>
          </p>
        <% end %>
    </div>
  </div>
</div>

app/views/prints/index.html.erb
<div class="container pb-5" data-controller="search">
  <div class="text-center mt-3">
    <h1>Shop</h1>
  </div>

   <div class="d-flex justify-content-center my-3 noshow">
    <%= form_with url: prints_path, method: :get, class: "d-flex", data: { search_target: 'searchForm' } do %>
      <div class="p-1 bg-light rounded rounded-pill shadow-sm mb-4">
          <div class="input-group">
            <input name="query" id="query" data-search-target="input" type="text" placeholder="What're you seeking?" data-search-target="search" class="form-control border-0 bg-light rounded-pill">
            <div class="input-group-append">
              <button type="submit" class="btn btn-link text-primary"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div class='d-flex justify-content-center'>
    <%= render 'reset_link', query: params[:query] %>
  </div>




  <div class="row row-cols-1 row-cols-md-2" id="products" data-controller="prints">
    <% @products.each do |product| %>

      <div class="col-sm-6 d-flex align-items-stretch">

        <div class="card my-5 mx-3 p-3 shadow rounded" data-action="click->prints#openProduct" data-id="<%= product["id"] %>" data-url="/prints/show/<%= product["id"] %>">

          <div class="ribbon"><span>Available</span></div>

          <%= image_tag product["image"] %>
          <div class="card-body">
              <h5 class="card-title"><%= product["title"] %></h5>
              <p class="card-text"><%= product["description"] %></p>
              <div class="d-flex flex-row price">
                  <small>
                    <%= number_to_currency(product["price"] / 100.00, :unit=> '$') %>
                  </small>
              </div>
            </div>
          <% if @prints_cart.include?(product) %>
            <p>In your cart <i class="fa-solid fa-cart-shopping"></i></p>
          <% end %>
        </div>

      </div>

    <% end %>
  </div>

  <div class="container pages-list">
    <%= paginate @products %>
  </div>



</div>

app/views/prints/prints_admin.html.erb
<div class="container-fluid pb-5">
  <div class="text-center">
    <h1>Shop Admin Panel</h1>
    <p>Here you can unpublish your prints via the API. Follow up in Printify dashboard to make sure they are removed.</p>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to admin_path, class: 'btn btn-sm rounded btn-success' do %>
      <i class="fa-solid fa-palette"></i>
      <p>Back to Paintings Admin</p>
    <% end %>
  </div>

  <div class="row" id="products" data-controller="prints">
    <% @products.each do |product| %>
      <div data-action="click->prints#openProduct" data-id="<%= product["id"] %>" data-url="/prints/show/<%= product["id"] %>">
        <div class="col-12">
          <div class="card-product mt-3 admin">
            <%= image_tag product["image"] %>

            <div class="card-product-infos">
              <h2><%= product["title"] %></h2>
              <div class="d-flex flex-row">
                <small>
                <%= number_to_currency(product["price"] / 100.00, :unit=> '$') %>
                </small>
              </div>
              <div class="d-flex flex-row gap-1">
                <%= link_to "Publish", publish_print_path(product["id"]), class: "btn btn-primary rounded mt-3 text-white" %>
                <%= link_to "Unpublish", unpublish_print_path(product["id"]), class: "btn btn-danger rounded mt-3 text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/prints/show.html.erb
<div class="container-fluid p-5 text-center" data-controller="prints">

    <% if false %>
      <div class="sticky" style="z-index: 2">
        <%= button_to add_to_cart_prints_path(@print["id"]), method: :post, class: "btn btn-outline-primary tree" do %>
          <i class="fa-solid fa-cart-plus fa-xl"></i>
          Purchase Item
        <% end %>
      </div>
    <% end %>

  <% singular = @print["images"].first %>
  <div id="productCarouselControls" class="carousel slide mt-3" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag singular, class: "carousel-img-responsive shadow rounded" %>
      </div>
      <% @print["images"][1..-1].each do |image| %>
        <div class="carousel-item">
          <%= image_tag image, class: "carousel-img-responsive shadow rounded"%>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" style="filter: invert(80%);" type="button" data-bs-target="#productCarouselControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" style="filter: invert(80%);" type="button" data-bs-target="#productCarouselControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

    <div class="my-3 text-center">
      <h1 class="mt-3 px-5"><%= @print["title"] %></h1>
      <% if @print["price"] >= 5000 %>
        <p class="prod-price"> <%= number_to_currency(@print["price"] / 100.00, :unit=> '$') %> <small>Shipping included</small></p>
      <% else %>
        <p class="prod-price"> <%= number_to_currency(@print["price"] / 100.00, :unit=> '$') %> <small>+ Shipping</small></p>
      <% end %>

      <p class="px-5"><%= @print["description"] %></p>

        <div class="d-flex flex-column gap-1 my-1 px-5 text-center col-md-6 mx-auto">

          <%= form_with url: add_to_cart_prints_path(@print["id"]), method: :post, local: true do |f| %>

            <% if !(@print["variants"].count < 2) && !@print['tags'].include?("Canvas" || "Framed") %>
               <p>Available Options:</p>
              <%= f.select :variant_id, @print['variants'].collect{ |v| [v['title'], v['id'].to_i] }, { selected: @print['variants'].first['id'] }, { class: "form-select border border-2 border-radius-lg", data: { action: "change->prints#updateVariant" }} %>
              <%= hidden_field_tag :variant_title, @print['variants'].first['title'], id: "variant_title", data: { prints_target: "title" } %>
            <% else %>
              <%= f.hidden_field :variant_id, value: @print['variants'].first['id'] %>
              <%= f.hidden_field :variant_title, value: @print['variants'].first['title'] %>
            <% end %>


            <% if @flat_cart_arr.any? { |print| print["id"] == @print["id"]} %>
              <div class="d-flex flex-column mt-3">
                <%= submit_tag "Add Another", class: "btn btn-lg btn-primary mb-2" %>
              </div>
            <% else %>
              <div class="d-flex flex-column mt-3">
                <%= submit_tag "Purchase Item", class: "btn btn-lg btn-outline-primary tree mt-3 mb-0" %>
              </div>
            <% end %>
          <% end %>
          <% if @flat_cart_arr.any? { |print| print["id"] == @print["id"]} %>
            <div class="d-flex flex-column mt-0">
               <%= button_to 'Remove from cart', remove_from_cart_prints_path(@print["id"]), method: :delete, class: 'btn btn-lg btn-danger mb-2' %>
            </div>
          <% end %>


        </div>






    </div>

</div>