config/routes.rb
Rails.application.routes.draw do
  get 'prints/index', to: 'prints#index', as: 'prints'
  get 'prints/prints_admin', to: 'prints#prints_admin', as: 'prints_admin'
  get 'prints/show/:id', to: 'prints#show', as: 'print'
  post '/add_to_cart_prints/:id', to: "prints#add_to_cart_prints", as: 'add_to_cart_prints'
  delete '/remove_from_cart_prints/:id', to: "prints#remove_from_cart_prints", as: 'remove_from_cart_prints'
  get '/publish_print/:id', to: "prints#publish_print", as: 'publish_print'
  get '/unpublish_print/:id', to: "prints#unpublish_print", as: 'unpublish_print'
  # resources :nfts, only: [ :index ] do
  #   collection do
  #     post 'set_image_urls'
  #     # get 'nfts'
  #   end
  # end
  # post '/set_image_urls', to: 'nfts#set_image_urls', as: 'set_image_urls'
  get '/nfts', to: 'nfts#nfts', as: 'nfts'
  get '/endpoint', to: 'nfts#endpoint', as: 'endpoint'


  resources :contacts, only: [:new, :create]

  resources :paintings
  get '/admin', to: 'paintings#admin', as: 'admin'
  devise_for :users, controllers: {
    sessions: 'custom_devise/sessions'
  }
  root to: "pages#home"
  get '/cv', to: "pages#cv", as: 'cv'
  get '/about', to: "pages#about", as: 'about'
  get '/commissions', to: "pages#commissions", as: 'commissions'
  get '/privacy', to: "pages#privacy", as: 'privacy'
  get '/terms', to: "pages#terms", as: 'terms'
  get '/photography', to: "pages#photography", as: 'photography'


  post '/add_to_cart/:id', to: "paintings#add_to_cart", as: 'add_to_cart'
  delete '/remove_from_cart/:id', to: "paintings#remove_from_cart", as: 'remove_from_cart'


  get '/orders/new', to: "orders#new", as: 'new_order'
  post '/orders', to: "orders#create", as: 'create_order'
  post :create_paypal , to: "orders#create_paypal"
  get '/orders/:id', to: "orders#show", as: 'order'
  get '/orders', to: "orders#index", as: 'orders'
  get '/orders/:id/edit', to: "orders#edit", as: 'edit_order'
  patch '/orders/:id', to: "orders#update", as: 'update_order'
  delete '/orders/:id', to: "orders#destroy", as: 'destroy_order'
  get '/alchemy', to: "orders#alchemy", as: 'alchemy'
  post '/total_price', to: "orders#total_price", as: 'total_price'
  post '/cancel_print_order', to: "orders#cancel_print_order", as: 'cancel_print_order'

  get '/wallet', to: "orders#wallet", as: 'wallet'
  get '/btcwallet', to: "orders#btcwallet", as: 'btcwallet'
end

app/models/painting.rb
class Painting < ApplicationRecord
  has_many_attached :photos
  belongs_to :order, optional: true
  validates :title, :description, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  enum :status, { available: 0, sold: 1 }
  paginates_per 10
end

app/controllers/paintings_controller.rb
require 'mail'
require 'json'
require 'uri'
require 'net/http'

class PaintingsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show add_to_cart remove_from_cart ]
  before_action :set_painting, only: %i[ show edit update destroy ]
  before_action :initalize_cart, only: %i[load_cart add_to_cart remove_from_cart ]
  before_action :load_cart # Load for all pages since in navbar, only: %i[ index show add_to_cart remove_from_cart ]
  # before_action :load_products, only: :load_cart_prints
  # before_action :load_cart_prints
  before_action :load_orders

  def index
    @paintings = Painting.all.order(created_at: :desc).page params[:page]

    return unless params[:query].present?

    sql_subquery = <<~SQL
      paintings.title ILIKE :query
    SQL
    @paintings = @paintings.where(sql_subquery, query: "%#{params[:query]}%").page params[:page]
  end

  def show
  end

  def new
    @painting = Painting.new
  end


  def edit
  end

  def create
    adjusted_params = painting_params.merge(price: painting_params[:price].to_i)
    @painting = Painting.new(adjusted_params)
    respond_to do |format|
      if @painting.save
        format.html { redirect_to painting_url(@painting), notice: "Painting was successfully created." }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to painting_url(@painting), notice: "Painting was successfully updated." }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: "Painting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def admin
    @paintings = Painting.all
  end


  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to new_order_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to paintings_path
  end

  private

   # @dev Cart functionality

  # @dev only display cart if the painting isn't in cart already (not etsy)
  def load_cart
    if session[:cart].nil?
      session[:cart] = []
      @cart = session[:cart]
    else
      @cart = Painting.find(session[:cart])
    end
  end

  def load_orders
    @orders = Order.all
  end

    def set_painting
      @painting = Painting.find(params[:id])
    end

    def painting_params
      params.require(:painting).permit(:description, :status, :price, :title, :discount_code, photos: [])
    end

    def initalize_cart
      session[:cart] ||= []
    end
end

app/views/paintings/_form.html.erb
<%= simple_form_for(@painting, data: { controller: 'price' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>

    <% if @painting.price? %>
      <%= f.input :price, data: { target: 'price.input' } %>
    <% else %>
      <%= f.input :price, label: 'Price in cents (ex: 10056 = $100.56)' %>
    <% end %>

    <%= f.input :title %>
    <%= f.input :status, collection: %w(sold available) %>
    <%= f.input :discount_code %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<div class="container-fluid mt-3 p-5 text-center">
  <div id="<%= dom_id painting %>">
    <% if painting.status != "sold" && !@cart.include?(painting) && false %>
      <div class="sticky">
        <%= button_to add_to_cart_path(painting), method: :post, class: "btn btn-outline-primary tree" do %>
          <i class="fa-solid fa-cart-plus fa-xl"></i>
          Purchase Original
        <% end %>
      </div>
    <% end %>

    <div class="mt-3">
      <% if Rails.env.test? %>
        <%= image_tag "photo1.jpeg", alt: "test image" %>
      <% else %>
        <%= cl_image_tag(painting.photos[0].key, class: "carousel-img-responsive shadow rounded") if painting.photos.present? %>
      <% end %>
    </div>

    <div class="my-3 text-center">
      <h1 class="mt-3"><%= painting.title %></h1>
      <p class="prod-price"> <%= number_to_currency(painting.price / 100.00, :unit=> '$') %> <small>Shipping included</small></p>
      <p><%= painting.description %></p>
      <% if @cart.include?(painting) %>
        <%= button_to 'Remove from cart', remove_from_cart_path(painting), method: :delete, class: 'btn btn-lg btn-outline-danger tree mt-3 mb-0' %>
      <% elsif painting.status == "sold" %>
        <p>
          <%= button_to "Sold", painting, class: "btn btn-danger mt-3", disabled: true %>
        </p>
      <% else %>
        <p>
          <%= button_to "Purchase Original", add_to_cart_path(painting), method: :post, class: "btn btn-lg btn-outline-primary tree mt-3 mb-0" %>
        </p>
      <% end %>
    </div>

  </div>
</div>

app/views/paintings/admin.html.erb
<div class="container-fluid pb-5">
  <div class="text-center">
    <h1>Paintings Admin Panel</h1>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to new_painting_path, class: 'btn btn-sm rounded btn-success' do %>
      <i class="fa-solid fa-plus"></i>
      <p>New Painting</p>
    <% end %>
  </div>

  <div class="row" id="paintings">
    <% @paintings.each do |painting| %>
      <% if !painting.order || painting.order.status != "complete" %>
        <%= link_to painting, style: "text-decoration: none;" do %>
          <div class="col-12">
            <div class="card-product no-hover mt-3">
              <%= cl_image_tag painting.photos[0].key if painting.photos.present? %>

              <div class="card-product-infos">
                <% if painting.status == "sold" %>
                  <h2 class="text-success fw-bold">🎉<%= painting.title %> - <%= painting.status.capitalize %>🎉</h2>
                <% else %>
                  <h2><%= painting.title %></h2>
                <% end %>

                <div class="d-flex flex-row">
                    <small>
                      <%= number_to_currency(painting.price / 100.00, :unit=> '$') %>
                    </small>
                </div>
                <div class="d-flex flex-row gap-1">
                  <%= link_to "Edit this painting", edit_painting_path(painting), class: "btn btn-primary btn-sm mt-3 text-white" %>
                  <%= link_to "Delete", painting, class: "btn btn-danger btn-sm mt-3 text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <%= link_to "Completed Sale: #{painting.title}", painting, class: "mt-3" %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/paintings/edit.html.erb
<div class="container-fluid pb-5 text-center">
  <h1>Editing painting</h1>

  <div class="d-flex justify-content-center">
     <%= render "form", painting: @painting %>
  </div>

  <br>

  <div>
    <%= link_to "Show this painting", @painting %> |
    <%= link_to "Back to paintings", paintings_path %>
  </div>
</div>

app/views/paintings/index.html.erb
<div class="container pb-5" data-controller="search">
  <div class="text-center mt-3">
    <h1>Jaleh's Originals</h1>
  </div>

 <div class="d-flex justify-content-center my-3">
    <%= form_with url: paintings_path, method: :get, class: "d-flex", data: { search_target: 'searchForm' } do %>
       <div class="p-1 bg-light rounded rounded-pill shadow-sm mb-4">
          <div class="input-group">
            <input name="query" id="query" data-search-target="input" type="text" placeholder="What're you seeking?" data-search-target="search" class="form-control border-0 bg-light rounded-pill">
            <div class="input-group-append">
              <button type="submit" class="btn btn-link text-primary"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div class='d-flex justify-content-center'>
    <%= render 'reset_link', query: params[:query] %>
  </div>


  <div class="row row-cols-1 row-cols-md-2" id="paintings" data-controller="works">
    <% @paintings.each do |painting| %>

      <div class="d-flex align-items-stretch">

        <div class="card my-5 mx-3 p-3 shadow rounded" data-action="click->works#openPainting" data-url="/paintings/<%= painting.id %>">
        <% if painting.status == 'available' %>
          <div class="ribbon"><span>Available</span></div>
        <% else %>
          <div class="ribbon red"><span>Sold</span></div>
        <% end %>
          <%= cl_image_tag painting.photos[0].key if painting.photos.present? %>
          <div class="card-body">
              <h5 class="card-title"><%= painting.title %></h5>
              <p class="card-text"><%= painting.description %></p>
              <div class="d-flex flex-row price">
                  <small>
                    <%= number_to_currency(painting.price / 100.00, :unit=> '$') %>
                  </small>
              </div>
            </div>
          <% if @cart.include?(painting) %>
            <p class="p-3">In your cart <i class="fa-solid fa-cart-shopping"></i></p>
          <% end %>
        </div>

      </div>

    <% end %>
  </div>
  <div class="container pages-list">
    <%= paginate @paintings %>
  </div>

</div>

app/views/paintings/new.html.erb
<div class="container-fluid pb-5">
  <h1>New painting</h1>

  <%= render "form", painting: @painting %>

  <br>

  <div>
    <%= link_to "Back to paintings", paintings_path %>
  </div>
</div>

app/views/paintings/show.html.erb
<div class="container-fluid pb-5 text-center">



  <%= render @painting %>

  <% if current_user %>
    <div>
      <%= link_to "Edit this painting", edit_painting_path(@painting), class: "btn btn-primary mt-3 text-white" %>
      <%= link_to "Back to paintings", paintings_path, class: "btn btn-info mt-3 text-white" %>

      <%= link_to "Delete", @painting, class: "btn btn-danger mt-3 text-white", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>
  <% end %>
</div>