config/routes.rb
Rails.application.routes.draw do
  get 'prints/index', to: 'prints#index', as: 'prints'
  get 'prints/prints_admin', to: 'prints#prints_admin', as: 'prints_admin'
  get 'prints/show/:id', to: 'prints#show', as: 'print'
  post '/add_to_cart_prints/:id', to: "prints#add_to_cart_prints", as: 'add_to_cart_prints'
  delete '/remove_from_cart_prints/:id', to: "prints#remove_from_cart_prints", as: 'remove_from_cart_prints'
  get '/publish_print/:id', to: "prints#publish_print", as: 'publish_print'
  get '/unpublish_print/:id', to: "prints#unpublish_print", as: 'unpublish_print'
  # resources :nfts, only: [ :index ] do
  #   collection do
  #     post 'set_image_urls'
  #     # get 'nfts'
  #   end
  # end
  # post '/set_image_urls', to: 'nfts#set_image_urls', as: 'set_image_urls'
  get '/nfts', to: 'nfts#nfts', as: 'nfts'
  get '/endpoint', to: 'nfts#endpoint', as: 'endpoint'


  resources :contacts, only: [:new, :create]

  resources :paintings
  get '/admin', to: 'paintings#admin', as: 'admin'
  devise_for :users, controllers: {
    sessions: 'custom_devise/sessions'
  }
  root to: "pages#home"
  get '/cv', to: "pages#cv", as: 'cv'
  get '/about', to: "pages#about", as: 'about'
  get '/commissions', to: "pages#commissions", as: 'commissions'
  get '/privacy', to: "pages#privacy", as: 'privacy'
  get '/terms', to: "pages#terms", as: 'terms'
  get '/photography', to: "pages#photography", as: 'photography'


  post '/add_to_cart/:id', to: "paintings#add_to_cart", as: 'add_to_cart'
  delete '/remove_from_cart/:id', to: "paintings#remove_from_cart", as: 'remove_from_cart'


  get '/orders/new', to: "orders#new", as: 'new_order'
  post '/orders', to: "orders#create", as: 'create_order'
  post :create_paypal , to: "orders#create_paypal"
  get '/orders/:id', to: "orders#show", as: 'order'
  get '/orders', to: "orders#index", as: 'orders'
  get '/orders/:id/edit', to: "orders#edit", as: 'edit_order'
  patch '/orders/:id', to: "orders#update", as: 'update_order'
  delete '/orders/:id', to: "orders#destroy", as: 'destroy_order'
  get '/alchemy', to: "orders#alchemy", as: 'alchemy'
  post '/total_price', to: "orders#total_price", as: 'total_price'
  post '/cancel_print_order', to: "orders#cancel_print_order", as: 'cancel_print_order'

  get '/wallet', to: "orders#wallet", as: 'wallet'
  get '/btcwallet', to: "orders#btcwallet", as: 'btcwallet'
end

app/views/shared/_cookies.html.erb
  <div data-controller="cookies">
    <div class="cookie-wrapper" data-cookies-target="wrapper">
      <header class="cookie-header">
        <i class="fa fa-cookie-bite"></i>
        <h2 class="cookie-header">Cookies Consent</h2>
      </header>

      <div class="cookie-data">
        <p>This website uses cookies to provide you with a more personalised and relevant browsing experience.<a
            href="/privacy"> Read More...</a></p>
      </div>

      <div class="cookie-buttons">
        <button class="cookie-button" id="acceptBtn" data-action="click->cookies#accept">Accept</button>
        <button class="cookie-button" id="declineBtn" data-action="click->cookies#reject">Decline</button>
      </div>
    </div>

  <% if false %>
   <div class="mailing-wrapper" data-cookies-target="mailing">
      <header class="mailing-header">
        <i class="fa fa-envelope"></i>
        <h2 class="mailing-header">Join my mailing list!</h2>
      </header>

        <div class="text-center mb-3">
          <div class="d-flex justify-content-center" id="mc_embed_shell">
              <form class="form-inline" action="https://jsadravi.us7.list-manage.com/subscribe/post?u=986ea8046b29fee65e34eda26&amp;id=c5725164da&amp;f_id=0096d2e4f0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank">

                  <input type="text" name="FNAME" id="mce-FNAME" value="" placeholder="First Name" aria-label="Recipient's first name">

                  <input type="email" id="mce-EMAIL" name="EMAIL"  placeholder="Your Email" aria-label="Recipient's Email" value="">

                  <button id="mc-embedded-subscribe" class="btn btn-outline-primary tree px-3 rounded-pill" type="submit" name="subscribe" value="Subscribe">Subscribe</button>

                <div aria-hidden="true" style="position: absolute; left: -5000px;">
                    /* real people should not fill this in and expect good things - do not remove this or risk form bot signups */
                    <input type="text" name="b_986ea8046b29fee65e34eda26_c5725164da" tabindex="-1" value="">
                </div>
              </form>

            <script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js"></script>
            <script type="text/javascript">(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
          </div>
        </div>

    </div>
  <% end %>



  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div data-controller="flash" class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div data-controller="flash" class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <% unless current_page?(root_path) %>
    <div class="footer mt-5">

        <div class="footer-links">
          <a href="https://www.patreon.com/jalehsart"><i class="fa-brands fa-patreon"></i></a>
          <a href="https://www.instagram.com/theartofjaleh/"><i class="fab fa-instagram"></i></a>
          <a href="https://www.facebook.com/theartofjaleh"><i class="fab fa-facebook"></i></a>
          <a href="https://twitter.com/TheArtofJaleh"><i class="fab fa-twitter"></i></a>
          <a href="https://www.linkedin.com/in/jalehsadravi/"><i class="fab fa-linkedin"></i></a>
          <a href="https://artofjaleh.substack.com?utm_source=navbar&utm_medium=web"><i class="bi bi-substack"></i></a>
        </div>


        <div class="ms-5">
          <p class="fp">
            Copyright © 2021-2024 Jaleh Sadravi. All rights reserved. The content of this website, including but not limited to paintings, images, and text, is protected by copyright law. Any unauthorized use or reproduction of the content without the written permission of the artist is prohibited.
          </p>

          <div class="d-flex justify-content-end">
            <p class="footer-copyright me-3">
              <%= link_to 'Terms & Conditions', terms_path %>
            </p>
            <p class="footer-copyright">
              <%= link_to 'Privacy Policy', privacy_path %>
            </p>
          </div>
        </div>

    </div>

  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon p-3">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag 'AOJ.png', class: "avatar" %>
      <small>The Art of Jaleh</small>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Paintings Admin", "/admin", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Shop Admin", "/prints/prints_admin", class: "nav-link" %>
          </li>
          <% if @orders.count > 0 && @orders.find_by(status: "open") != nil %>
             <%= link_to orders_path, class: "btn btn-success rounded position-relative me-3 mb-3" do %>
                <i class="fa-solid fa-truck-fast"></i> <span class="position-absolute top-0 start-100 translate-middle badge bg-secondary rounded-pill"><%= @orders.where(status: "open").count %></span>
              <% end %>
          <% end %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "aoj.jpeg", class: "avatar-lg", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Originals", paintings_path, class: "dropdown-item" %>
              <%= link_to "About", "/about", class: "dropdown-item" %>
              <%= link_to "CV", "/cv", class: "dropdown-item" %>
              <%= link_to "Photography", "/photography", class: "dropdown-item" %>
              <%= link_to "Orders", "/orders", class: "dropdown-item" %>
              <%= link_to "Commissions", "/commissions", class: "dropdown-item" %>
              <%= link_to "NFTs", "/nfts", class: "dropdown-item" %>
              <%= link_to "Shop", "/prints/index", class: "dropdown-item" %>
              <%= link_to "Contact", new_contact_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <% if defined?(@cart) && defined?(@prints_cart) %>
            <% if @cart && @cart.count > 0 || @prints_cart && @cart.count > 0 || @cart && @prints_cart.count > 0 || @prints_cart && @prints_cart.count > 0%>
              <li class="nav-item">
                <%= link_to new_order_path, class: "btn btn-primary rounded" do %>
                  <i class="fa-solid fa-cart-shopping me-3"></i><span class="badge bg-secondary"><%= @cart.count + @prints_cart.count %></span>
                <% end %>
              </li>
            <% end %>
          <% end %>
          <li class="nav-item">
            <%= link_to "Originals", paintings_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Shop", prints_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "NFTs", nfts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "CV", cv_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Commissions", commissions_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", new_contact_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%# Path to view photography. Add before last "end" above if desired %>

<% if false %>
      <li class="nav-item">
            <%= link_to "Photography", photography_path, class: "nav-link" %>
          </li>
<% end %>